### ISSUE TITLE
slow performance

### ISSUE THREAD

**Issue by segator** [kanocz/lcvpn#10]
iperf    on direct connection got 900mbps  (1ms)
with  lcvpn 500mbps

iperf over internet 600mbps stables between 2 servers(50ms)
with lcvpn 30mbps

Why this diference?

**Comment by kanocz** [comment]
@segator do you have zero packet loss? tested now between Prague and Berlin and have about 200mbps - same result as with 2 servers in one datacenter... other idea is about MTU - is there some router with lower MTU than 1500? if yes there will be fragmentation and defragmentation which can affect speed

**Comment by segator** [comment]
No packet loss, direct iperf have good speed, tried with diferents mtu, same results

**Comment by kanocz** [comment]
@segator hard to say :-( what about cpu load and memory usage? I really can't see any possible problem as lcvpn use UDP transport, so no confirmation needed on packet receive an so on - each packet is individual and just "encrypted/decrypted and forwarded to other interface"

**Comment by segator** [comment]
Cpu usage its not on the max usage, 30-50%

**Comment by segator** [comment]
after set high send recv threads performance is good
