### ISSUE TITLE
connect through firewall (no port forwarding)

### ISSUE THREAD

**Issue by YoSev** [kanocz/lcvpn#16]
Hey,

can two servers connect to each other, if server 1 can contact server 2 but not the other way around due to firewall restrictions / missing port forwarding?

As Server 1 connects to Server 2, Server 2 should not need to connect to Server 1 anymore right (even tho it can't)?

I tried to set it up but i failed. No connection established between both hosts.

**Comment by kanocz** [comment]
hi @john-dev , problem is that lcvpn doesn't use "connection" - it sends packets via UDP and assumes that both servers use "white ip" or in worst case have forwarded port
there are many other "connection-based" solutions exists and can be used (like openvpn, wireguard and so on) in your case - adding NAT support and so on will increase code-base more twice and it will be much more hard to check and analyze :(

**Comment by YoSev** [comment]
I see.. I assumed the UDP would use a kind of conenction state like TCP does too.
UDP Holepunching would  be appreciated but i saw there is already a ticket.

I have to think this over, maybe tcp would be the better approach for me in thise case. Anyway, i love your project.
