### ISSUE TITLE
Error: Unable to get UDP socket: unknown port udp/

### ISSUE THREAD

**Issue by nejtr0n** [kanocz/lcvpn#3]
Hello.
I've got error: "Unable to get UDP socket: unknown port udp/"

Machine: virtualbox
ip: 192.168.1.50
conf: 
[main]
port = 1234
aeskey =  A3E8DD8E33C0887C6A86EF47AF6B008C00508B00FA18666658EBB2805D2BFF48
# altkey = 1111111117C32FC42F1CEB0CAA54D40E9D1EEDAF14EBCBCECA429E1B2EF72D21

broadcast = 10.0.0.255
netcidr = 24
recvThreads = 4
sendThreads = 4

[remote "phy1.dc1"]
ExtIP = 192.168.1.50
LocIP = 10.0.0.1

Start:
/home/golang/bin/lcvpn -config /etc/lcvpn.conf -local phy1.dc1

Error:
2016/04/29 14:29:08 Interface allocated: tun0
2016/04/29 14:29:08 Interface parameters configured
2016/04/29 14:29:08 Unable to get UDP socket: unknown port udp/

It appears after update host kernel to 4.4.0-21-generic.

I've tried to change port to another - same errror.
Any ideas how to fix it?

**Comment by nejtr0n** [comment]
Changed virtual machine kernel to 4.4.0-21-generic - error disappears.
I think it is proplem of virtual environment, but not lcvpn. (But it seems to be strange)

**Comment by kanocz** [comment]
If you can give me version of guest operating system I can try to setup the same one in virtualbox (which version?) and replicate error

**Comment by nejtr0n** [comment]
Hello. This is my environment:
Host: Ubuntu 16.04
Linux a6y-work 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Virtualbox:
Debian 8.3
Linux phy1.dc1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

**Comment by kanocz** [comment]
can't get this error at all :-(
which version of golang do you use to build lcvpn?

**Comment by nejtr0n** [comment]
Go version is 1.6
root@phy1:/usr/local/go/bin# ./go version
go version go1.6 linux/amd64

I think this is virtualbox associated bug. 
It is not critical, because virtualbox is only test environment.

**Comment by nejtr0n** [comment]
I will try to reproduce it on home machine (now I'm at work) and to share you acces to shell.

**Comment by kanocz** [comment]
ok, thank you
not critical, but it's interesting :)

**Comment by nejtr0n** [comment]
I think you could close that issue. Could not reproduce it in another computer (only my work station is "bugged"). And I could not port forward ssh to VM here (Security policy of company). If somebedy will face that bug, it would be confirmation of it. 
I'm sorry to trouble you.

**Comment by kanocz** [comment]
ok, so closing issue
