### ISSUE TITLE
It can be use for my scene?

### ISSUE THREAD

**Issue by paulocoutinhox** [kanocz/lcvpn#6]
Hi,

I have a scene that i need solve with VPN. My home raspberry need connect to my VPN on amazon and my customers need connect their pc/ios/android devices to that same VPN on amazon to access to raspberry.

How i can do it with this tool?

Thanks.

**Comment by kanocz** [comment]
I'm afraid that it's not a suitable solution as it designed for usage in static IPs not hidden behind NAT. probably openvpn or pptp/l2tp fits better in your case and already has support on mobile platforms.

**Comment by paulocoutinhox** [comment]
Ok man, thanks. Im trying configure openvpn, but cant connect from mac because auth problems that i dont know more what to do to solve it. But thanks.
