### ISSUE TITLE
Porting freebsd/macos

### ISSUE THREAD

**Issue by FrankIT60** [kanocz/lcvpn#8]
Ciao Kanocz,
you thought about porting it to freebsd/macos ?

Thanks.

**Comment by kanocz** [comment]
hm... looks like OSx is not a problem, but I'm afraid that FreeBSD will be not so easy :(
and a question if somebody needs it on OSx as it's designed to work on servers, not on desktops

**Comment by FrankIT60** [comment]
there are, I think a few, mac osx server. We have one :-)

**Comment by kanocz** [comment]
@FrankIT60  First test version for macos is committed, please test if you still need it and re-open ticket if you'll find any problems... Thanks
