### ISSUE TITLE
encounter error on mac os x

### ISSUE THREAD

**Issue by luckypoem** [kanocz/lcvpn#9]
hi.
after i ran "go get -u -v github.com/kanocz/lcvpn" under $GOPATH,
it shows:
...
# github.com/kanocz/lcvpn
src/github.com/kanocz/lcvpn/iface.go:26:16: undefined: water.NewTUN
src/github.com/kanocz/lcvpn/iface.go:35:15: undefined: tenus.NewLinkFrom
src/github.com/kanocz/lcvpn/iface.go:89:11: undefined: "github.com/kanocz/lcvpn/netlink".DelRoute
yudeMacBook-Air:gopath brite$ 

how to fix the errors?

**Comment by kanocz** [comment]
for now lcvpn works only on Linux (it's specified in readme)
I'm thinking about adding support of osx and freebsd, but have no eta yet

**Comment by kanocz** [comment]
in fact duplicate od #8
